"""add user, project, and other models

Revision ID: 0770d4d29930
Revises: 20260323_000001
Create Date: 2026-04-06 23:21:20.258824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0770d4d29930'
down_revision: Union[str, None] = '20260323_000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests_id'), table_name='tests')
    op.drop_table('tests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tests_pkey')),
    sa.UniqueConstraint('name', name=op.f('tests_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    # ### end Alembic commands ###
