"""add project id to coworking_times

Revision ID: e84959d7ea3b
Revises: 1826b613b7b9
Create Date: 2026-04-26 12:28:37.999472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84959d7ea3b'
down_revision: Union[str, None] = '1826b613b7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coworking_times', sa.Column('project_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'coworking_times', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coworking_times', type_='foreignkey')
    op.drop_column('coworking_times', 'project_id')
    # ### end Alembic commands ###
